import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Form1 from "@/components/Form1";
import Form2 from "@/components/Form2";
import Form3 from "@/components/Form3";
import Side1 from "@/components/Side1";
import Side2 from "@/components/Side2";
import { useState } from "react";


export default function Home() {
  const tsTime = 500;
  const [moving, setMoving] = useState(false);
  const [cardActive, setCardActive] = useState(true);
  const [form1Active, setForm1Active] = useState(true);
  const [form2Active, setForm2Active] = useState(false);
  const [form3Active, setForm3Active] = useState(false);
  const [form1Show, setForm1Show] = useState(true);
  const [form2Show, setForm2Show] = useState(false);
  const [form3Show, setForm3Show] = useState(false);
  const [side1Active, setSide1Active] = useState(true);
  const [side2Active, setSide2Active] = useState(false);

  const wait = (t) => {
    return new Promise(resolve => {
      setTimeout(()=>{
        resolve();
      }, t);
    });
  }

  const loginToForget = async () => {
    if(moving) return;
    setMoving(true);
    setForm3Show(true);
    await wait(10);
    setForm1Active(false);
    setForm3Active(true);
    await wait(tsTime);
    setForm1Show(false);
    setMoving(false);
  }

  const forgetToLogin = async () => {
    if(moving) return;
    setMoving(true);
    setForm1Show(true);
    await wait(10);
    setForm3Active(false);
    setForm1Active(true);
    await wait(tsTime);
    setForm3Show(false);
    setMoving(false);
  }

  const loginToRegister = async () => {
    if(moving) return;
    setMoving(true);

    setCardActive(false);
    setSide1Active(false);
    await wait(tsTime);
    setForm2Show(true);
    await wait(10);
    setForm1Active(false);
    setForm2Active(true);
    await wait(tsTime);
    setForm1Show(false);
    setSide2Active(true);
    setCardActive(true);

    setMoving(false);
  }

  const registerToLogin = async () => {
    if(moving) return;
    setMoving(true);
    setCardActive(false);
    setSide2Active(false);
    await wait(tsTime);
    setForm1Show(true);
    await wait(10);
    setForm2Active(false);
    setForm1Active(true);
    await wait(tsTime);
    setForm2Show(false);
    setSide1Active(true);
    setCardActive(true);
    setMoving(false);
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container container ${styles.mh100dvh} d-flex justify-content-center align-items-center`}>
        <div className={`card ${styles.card1} ${cardActive==true?styles.active:""}`}>
          <div className="card-body p-0 d-flex flex-nowrap ">
            <Side1 active={side1Active} />
            <Side2 active={side2Active} />
            <Form2 registerToLogin={registerToLogin} active={form2Active} show={form2Show} />
            <Form3 forgetToLogin={forgetToLogin} active={form3Active} show={form3Show} />
            <Form1 loginToRegister={loginToRegister} loginToForget={loginToForget} active={form1Active} show={form1Show} />
          </div>
        </div>
      </main>
    </>
  );
}
